FROM winglian/axolotl-cloud:main-latest

RUN pip install mlflow huggingface_hub wandb

WORKDIR /workspace/axolotl
RUN mkdir -p /workspace/axolotl/configs \
    /workspace/axolotl/outputs \
    /workspace/axolotl/data \
    /workspace/input_data

ENV HUGGINGFACE_TOKEN=""
ENV WANDB_TOKEN=""
ENV JOB_ID=""
ENV DATASET_TYPE=""
ENV DATASET_FILENAME=""
ENV CONFIG_DIR="/workspace/axolotl/configs"
ENV OUTPUT_DIR="/workspace/axolotl/outputs"

CMD echo 'Preparing data...' && \
    pip install mlflow && \
    pip install --upgrade huggingface_hub && \
    if [ -n "$HUGGINGFACE_TOKEN" ]; then \
        echo "Attempting to log in to Hugging Face" && \
        huggingface-cli login --token "$HUGGINGFACE_TOKEN" --add-to-git-credential; \
    else \
        echo "HUGGINGFACE_TOKEN is not set. Skipping Hugging Face login."; \
    fi && \
    if [ -n "$WANDB_TOKEN" ]; then \
        echo "Attempting to log in to W&B" && \
        wandb login "$WANDB_TOKEN"; \
    else \
        echo "WANDB_TOKEN is not set. Skipping W&B login."; \
    fi && \
    if [ "$DATASET_TYPE" != "hf" ] && [ -f "/workspace/input_data/${DATASET_FILENAME}" ]; then \
        cp /workspace/input_data/${DATASET_FILENAME} /workspace/axolotl/data/${DATASET_FILENAME}; \
    fi && \
    echo 'Starting training command' && \
    accelerate launch -m axolotl.cli.train ${CONFIG_DIR}/${JOB_ID}.yml